export const DATA_FETCH_REQUESTED = 'DATA_FETCH_REQUESTED';
export const DATA_FETCH_SUCCEEDED = 'DATA_FETCH_SUCCEEDED';
export const SPECIFIC_DATA_REQUESTED = 'SPECIFIC_DATA_REQUESTED';
export const SPECIFIC_DATA_SUCCEEDED = 'SPECIFIC_DATA_SUCCEEDED';
